// CustomFieldValue domain model.
//
// Immutable representation of a per-notation value for one custom field,
// as returned by [CustomFieldRepository]. Uses a sparse column design:
// only the column matching the field's type is populated. JSON serialization
// is generated by json_serializable.
//
// Run `dart run build_runner build --delete-conflicting-outputs` to regenerate
// custom_field_value.g.dart.

import 'package:json_annotation/json_annotation.dart';

part 'custom_field_value.g.dart';

/// Immutable domain model for a per-notation custom field value.
///
/// Corresponds to the `notation_custom_fields` table. Uses a sparse column
/// design: exactly one of [valueText], [valueNumber], [valueDate], or
/// [valueBoolean] should be populated, matching the [CustomFieldDefinition]
/// field type. All others will be null.
///
/// The composite primary key is ([notationId], [definitionId]).
@JsonSerializable(fieldRename: FieldRename.snake)
class CustomFieldValue {
  /// Creates an immutable [CustomFieldValue].
  ///
  /// Parameters:
  /// - [notationId]: Foreign key referencing the parent notation.
  /// - [definitionId]: Foreign key referencing the field definition.
  /// - [valueText]: Text value; populated when `field_type = 'text'`.
  /// - [valueNumber]: Numeric value; populated when `field_type = 'number'`.
  /// - [valueDate]: ISO 8601 date value; populated when `field_type = 'date'`.
  /// - [valueBoolean]: Boolean value; populated when `field_type = 'boolean'`.
  const CustomFieldValue({
    required this.notationId,
    required this.definitionId,
    this.valueText,
    this.valueNumber,
    this.valueDate,
    this.valueBoolean,
  });

  /// Foreign key referencing the parent notation.
  final String notationId;

  /// Foreign key referencing the [CustomFieldDefinition].
  final String definitionId;

  /// Text value; populated when the field type is `text`.
  final String? valueText;

  /// Numeric value (double); populated when the field type is `number`.
  final double? valueNumber;

  /// ISO 8601 date value; populated when the field type is `date`.
  final String? valueDate;

  /// Boolean value; populated when the field type is `boolean`.
  final bool? valueBoolean;

  /// Returns a copy of this [CustomFieldValue] with the specified fields
  /// replaced.
  ///
  /// Fields not provided retain their current values.
  CustomFieldValue copyWith({
    String? notationId,
    String? definitionId,
    String? valueText,
    double? valueNumber,
    String? valueDate,
    bool? valueBoolean,
  }) =>
      CustomFieldValue(
        notationId: notationId ?? this.notationId,
        definitionId: definitionId ?? this.definitionId,
        valueText: valueText ?? this.valueText,
        valueNumber: valueNumber ?? this.valueNumber,
        valueDate: valueDate ?? this.valueDate,
        valueBoolean: valueBoolean ?? this.valueBoolean,
      );

  /// Deserializes a [CustomFieldValue] from a JSON map.
  factory CustomFieldValue.fromJson(Map<String, dynamic> json) =>
      _$CustomFieldValueFromJson(json);

  /// Serializes this [CustomFieldValue] to a JSON map.
  Map<String, dynamic> toJson() => _$CustomFieldValueToJson(this);

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CustomFieldValue &&
          runtimeType == other.runtimeType &&
          notationId == other.notationId &&
          definitionId == other.definitionId &&
          valueText == other.valueText &&
          valueNumber == other.valueNumber &&
          valueDate == other.valueDate &&
          valueBoolean == other.valueBoolean;

  @override
  int get hashCode => Object.hash(
        notationId,
        definitionId,
        valueText,
        valueNumber,
        valueDate,
        valueBoolean,
      );

  @override
  String toString() => 'CustomFieldValue(notationId: $notationId, '
      'definitionId: $definitionId)';
}
