// InstrumentInstance domain model.
//
// Immutable representation of a specific instrument owned by the user, as
// returned by [InstrumentRepository]. JSON serialization is generated by
// json_serializable.
//
// Run `dart run build_runner build --delete-conflicting-outputs` to regenerate
// instrument_instance.g.dart.

import 'package:json_annotation/json_annotation.dart';

part 'instrument_instance.g.dart';

/// Immutable domain model for a specific instrument instance.
///
/// An instance represents one physical instrument owned by the user. It
/// belongs to an [InstrumentClass] via [classId]. Soft-delete ([deletedAt]
/// non-null) means the instrument is archived: it remains visible on existing
/// notations but is hidden from active instrument lists.
@JsonSerializable(fieldRename: FieldRename.snake)
class InstrumentInstance {
  /// Creates an immutable [InstrumentInstance].
  ///
  /// Parameters:
  /// - [id]: UUIDv4 generated at the app layer.
  /// - [classId]: Foreign key to the parent [InstrumentClass].
  /// - [brand]: Optional brand name; nullable.
  /// - [model]: Optional model name; nullable.
  /// - [colorHex]: Catppuccin hex color for UI display.
  /// - [priceInr]: Purchase price in INR; nullable.
  /// - [photoPath]: Relative path to an instrument photo; nullable.
  /// - [notes]: Free-form notes about this instrument.
  /// - [createdAt]: ISO 8601 datetime of creation.
  /// - [updatedAt]: ISO 8601 datetime of last update.
  /// - [deletedAt]: Archive timestamp; null means active.
  const InstrumentInstance({
    required this.id,
    required this.classId,
    this.brand,
    this.model,
    required this.colorHex,
    this.priceInr,
    this.photoPath,
    required this.notes,
    required this.createdAt,
    required this.updatedAt,
    this.deletedAt,
  });

  /// UUIDv4 generated at the app layer.
  final String id;

  /// Foreign key referencing the parent [InstrumentClass].
  final String classId;

  /// Optional brand name, e.g. `'Yamaha'`; nullable.
  final String? brand;

  /// Optional model name, e.g. `'C40'`; nullable.
  final String? model;

  /// Catppuccin hex color string for UI display, e.g. `'#cba6f7'`.
  final String colorHex;

  /// Purchase price in INR (whole number); nullable.
  final int? priceInr;

  /// Relative path to a photo of this instrument; nullable.
  final String? photoPath;

  /// Free-form notes about this instrument.
  final String notes;

  /// ISO 8601 datetime when this instance was created.
  final String createdAt;

  /// ISO 8601 datetime of the last update.
  final String updatedAt;

  /// Archive (soft-delete) timestamp. Null means active.
  final String? deletedAt;

  /// Returns a copy of this [InstrumentInstance] with the specified fields
  /// replaced.
  ///
  /// Fields not provided retain their current values.
  InstrumentInstance copyWith({
    String? id,
    String? classId,
    String? brand,
    String? model,
    String? colorHex,
    int? priceInr,
    String? photoPath,
    String? notes,
    String? createdAt,
    String? updatedAt,
    String? deletedAt,
  }) =>
      InstrumentInstance(
        id: id ?? this.id,
        classId: classId ?? this.classId,
        brand: brand ?? this.brand,
        model: model ?? this.model,
        colorHex: colorHex ?? this.colorHex,
        priceInr: priceInr ?? this.priceInr,
        photoPath: photoPath ?? this.photoPath,
        notes: notes ?? this.notes,
        createdAt: createdAt ?? this.createdAt,
        updatedAt: updatedAt ?? this.updatedAt,
        deletedAt: deletedAt ?? this.deletedAt,
      );

  /// Deserializes an [InstrumentInstance] from a JSON map.
  factory InstrumentInstance.fromJson(Map<String, dynamic> json) =>
      _$InstrumentInstanceFromJson(json);

  /// Serializes this [InstrumentInstance] to a JSON map.
  Map<String, dynamic> toJson() => _$InstrumentInstanceToJson(this);

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is InstrumentInstance &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          classId == other.classId &&
          brand == other.brand &&
          model == other.model &&
          colorHex == other.colorHex &&
          priceInr == other.priceInr &&
          photoPath == other.photoPath &&
          notes == other.notes &&
          createdAt == other.createdAt &&
          updatedAt == other.updatedAt &&
          deletedAt == other.deletedAt;

  @override
  int get hashCode => Object.hash(
        id,
        classId,
        brand,
        model,
        colorHex,
        priceInr,
        photoPath,
        notes,
        createdAt,
        updatedAt,
        deletedAt,
      );

  @override
  String toString() =>
      'InstrumentInstance(id: $id, classId: $classId, brand: $brand, '
      'model: $model)';
}
