// InstrumentClass domain model.
//
// Immutable representation of an instrument class (e.g. String, Wind,
// Percussion) as returned by [InstrumentRepository]. JSON serialization is
// generated by json_serializable.
//
// Run `dart run build_runner build --delete-conflicting-outputs` to regenerate
// instrument_class.g.dart.

import 'package:json_annotation/json_annotation.dart';

part 'instrument_class.g.dart';

/// Immutable domain model for an instrument class definition.
///
/// Instrument classes group instrument instances (e.g. a sitar belongs to
/// the "String" class). Deleting a class is blocked while any
/// [InstrumentInstance] rows reference it.
@JsonSerializable(fieldRename: FieldRename.snake)
class InstrumentClass {
  /// Creates an immutable [InstrumentClass] instance.
  ///
  /// Parameters:
  /// - [id]: UUIDv4 generated at the app layer.
  /// - [name]: Unique human-readable class name.
  /// - [createdAt]: ISO 8601 datetime of creation.
  /// - [updatedAt]: ISO 8601 datetime of last update.
  const InstrumentClass({
    required this.id,
    required this.name,
    required this.createdAt,
    required this.updatedAt,
  });

  /// UUIDv4 generated at the app layer.
  final String id;

  /// Unique human-readable class name, e.g. `'String'` or `'Percussion'`.
  final String name;

  /// ISO 8601 datetime when this class was created.
  final String createdAt;

  /// ISO 8601 datetime of the last update to this class.
  final String updatedAt;

  /// Returns a copy of this [InstrumentClass] with the specified fields
  /// replaced.
  ///
  /// Fields not provided retain their current values.
  InstrumentClass copyWith({
    String? id,
    String? name,
    String? createdAt,
    String? updatedAt,
  }) =>
      InstrumentClass(
        id: id ?? this.id,
        name: name ?? this.name,
        createdAt: createdAt ?? this.createdAt,
        updatedAt: updatedAt ?? this.updatedAt,
      );

  /// Deserializes an [InstrumentClass] from a JSON map.
  factory InstrumentClass.fromJson(Map<String, dynamic> json) =>
      _$InstrumentClassFromJson(json);

  /// Serializes this [InstrumentClass] to a JSON map.
  Map<String, dynamic> toJson() => _$InstrumentClassToJson(this);

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is InstrumentClass &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          createdAt == other.createdAt &&
          updatedAt == other.updatedAt;

  @override
  int get hashCode => Object.hash(id, name, createdAt, updatedAt);

  @override
  String toString() => 'InstrumentClass(id: $id, name: $name)';
}
