// NotationPage domain model.
//
// Immutable representation of a single page image within a notation, as
// returned by [NotationPageRepository]. JSON serialization is generated by
// json_serializable.
//
// Run `dart run build_runner build --delete-conflicting-outputs` to regenerate
// notation_page.g.dart.

import 'package:json_annotation/json_annotation.dart';

part 'notation_page.g.dart';

/// Immutable domain model for a single page within a [Notation].
///
/// Each page stores a relative image path and non-destructive render
/// parameters (filter, crop, rotation). The original image at [imagePath]
/// is never mutated; [renderParams] is applied at render time.
@JsonSerializable(fieldRename: FieldRename.snake)
class NotationPage {
  /// Creates an immutable [NotationPage] instance.
  ///
  /// Parameters:
  /// - [id]: UUIDv4 generated at the app layer.
  /// - [notationId]: Foreign key referencing the parent notation.
  /// - [pageOrder]: 0-indexed position within the notation.
  /// - [imagePath]: Path relative to the app documents directory.
  /// - [renderParams]: Serialized JSON with non-destructive render settings.
  /// - [createdAt]: ISO 8601 datetime of creation.
  const NotationPage({
    required this.id,
    required this.notationId,
    required this.pageOrder,
    required this.imagePath,
    required this.renderParams,
    required this.createdAt,
  });

  /// UUIDv4 generated at the app layer.
  final String id;

  /// Foreign key referencing the parent notation.
  final String notationId;

  /// 0-indexed position of this page within the notation.
  final int pageOrder;

  /// Path relative to `getApplicationDocumentsDirectory()`.
  ///
  /// Example: `notations/<notation_id>/page_<id>_original.jpg`.
  final String imagePath;

  /// Serialized [RenderParams] JSON.
  ///
  /// Contains non-destructive render settings (filter, crop rect, rotation).
  /// The original image at [imagePath] is never mutated.
  final String renderParams;

  /// ISO 8601 datetime when this row was created.
  final String createdAt;

  /// Returns a copy of this [NotationPage] with the specified fields replaced.
  ///
  /// Fields not provided retain their current values.
  NotationPage copyWith({
    String? id,
    String? notationId,
    int? pageOrder,
    String? imagePath,
    String? renderParams,
    String? createdAt,
  }) =>
      NotationPage(
        id: id ?? this.id,
        notationId: notationId ?? this.notationId,
        pageOrder: pageOrder ?? this.pageOrder,
        imagePath: imagePath ?? this.imagePath,
        renderParams: renderParams ?? this.renderParams,
        createdAt: createdAt ?? this.createdAt,
      );

  /// Deserializes a [NotationPage] from a JSON map.
  factory NotationPage.fromJson(Map<String, dynamic> json) =>
      _$NotationPageFromJson(json);

  /// Serializes this [NotationPage] to a JSON map.
  Map<String, dynamic> toJson() => _$NotationPageToJson(this);

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is NotationPage &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          notationId == other.notationId &&
          pageOrder == other.pageOrder &&
          imagePath == other.imagePath &&
          renderParams == other.renderParams &&
          createdAt == other.createdAt;

  @override
  int get hashCode => Object.hash(
        id,
        notationId,
        pageOrder,
        imagePath,
        renderParams,
        createdAt,
      );

  @override
  String toString() =>
      'NotationPage(id: $id, notationId: $notationId, pageOrder: $pageOrder)';
}
