// Notation domain model.
//
// Immutable representation of a sargam notation entry as returned by
// [NotationRepository]. All fields are final; mutations are performed via
// [copyWith]. JSON serialization is generated by json_serializable.
//
// Run `dart run build_runner build --delete-conflicting-outputs` to regenerate
// the companion file notation.g.dart.

import 'package:json_annotation/json_annotation.dart';

part 'notation.g.dart';

/// Immutable domain model for a sargam notation.
///
/// Represents one piece of music with its metadata. Artists and languages
/// are stored as ordered lists. Nullable fields are absent from the original
/// data (e.g., the user has not set a key signature yet).
///
/// The [deletedAt] field implements soft-delete: a non-null value means the
/// notation is in the trash and should be hidden from normal queries.
@JsonSerializable(fieldRename: FieldRename.snake)
class Notation {
  /// Creates an immutable [Notation] instance.
  ///
  /// Parameters:
  /// - [id]: UUIDv4 generated at the app layer.
  /// - [title]: Human-readable title of the piece.
  /// - [artists]: Ordered list of artist names; defaults to empty.
  /// - [dateWritten]: ISO 8601 date (YYYY-MM-DD); nullable.
  /// - [timeSig]: Time signature string, e.g. `'4/4'`; nullable.
  /// - [keySig]: Key signature string, e.g. `'C'`; nullable.
  /// - [languages]: Ordered list of language names; defaults to empty.
  /// - [notes]: Free-form personal notes.
  /// - [playCount]: Number of times the piece has been played.
  /// - [lastPlayedAt]: ISO 8601 datetime of last play; nullable.
  /// - [createdAt]: ISO 8601 datetime of creation.
  /// - [updatedAt]: ISO 8601 datetime of last update.
  /// - [deletedAt]: Soft-delete timestamp; null means active.
  const Notation({
    required this.id,
    required this.title,
    required this.artists,
    this.dateWritten,
    this.timeSig,
    this.keySig,
    required this.languages,
    required this.notes,
    required this.playCount,
    this.lastPlayedAt,
    required this.createdAt,
    required this.updatedAt,
    this.deletedAt,
  });

  /// UUIDv4 generated at the app layer.
  final String id;

  /// Human-readable title of the piece.
  final String title;

  /// Ordered list of artist names.
  final List<String> artists;

  /// ISO 8601 date (YYYY-MM-DD) when the notation was written; nullable.
  final String? dateWritten;

  /// Time signature string, e.g. `'4/4'` or `'6/8'`; nullable.
  final String? timeSig;

  /// Key signature string, e.g. `'C'` or `'Bb minor'`; nullable.
  final String? keySig;

  /// Ordered list of language names, e.g. `['Hindi']`.
  final List<String> languages;

  /// Free-form personal notes about this notation.
  final String notes;

  /// Number of times this notation has been played.
  final int playCount;

  /// ISO 8601 datetime of the last play session; nullable.
  final String? lastPlayedAt;

  /// ISO 8601 datetime when this row was created.
  final String createdAt;

  /// ISO 8601 datetime of the last update.
  final String updatedAt;

  /// Soft-delete timestamp. Null means active; non-null means trashed.
  final String? deletedAt;

  /// Returns a copy of this [Notation] with the specified fields replaced.
  ///
  /// Fields not provided retain their current values.
  Notation copyWith({
    String? id,
    String? title,
    List<String>? artists,
    String? dateWritten,
    String? timeSig,
    String? keySig,
    List<String>? languages,
    String? notes,
    int? playCount,
    String? lastPlayedAt,
    String? createdAt,
    String? updatedAt,
    String? deletedAt,
  }) =>
      Notation(
        id: id ?? this.id,
        title: title ?? this.title,
        artists: artists ?? this.artists,
        dateWritten: dateWritten ?? this.dateWritten,
        timeSig: timeSig ?? this.timeSig,
        keySig: keySig ?? this.keySig,
        languages: languages ?? this.languages,
        notes: notes ?? this.notes,
        playCount: playCount ?? this.playCount,
        lastPlayedAt: lastPlayedAt ?? this.lastPlayedAt,
        createdAt: createdAt ?? this.createdAt,
        updatedAt: updatedAt ?? this.updatedAt,
        deletedAt: deletedAt ?? this.deletedAt,
      );

  /// Deserializes a [Notation] from a JSON map.
  ///
  /// Returns a new [Notation] instance populated from [json].
  factory Notation.fromJson(Map<String, dynamic> json) =>
      _$NotationFromJson(json);

  /// Serializes this [Notation] to a JSON map.
  ///
  /// Returns a [Map<String, dynamic>] suitable for storage or transmission.
  Map<String, dynamic> toJson() => _$NotationToJson(this);

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Notation &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          title == other.title &&
          _listEquals(artists, other.artists) &&
          dateWritten == other.dateWritten &&
          timeSig == other.timeSig &&
          keySig == other.keySig &&
          _listEquals(languages, other.languages) &&
          notes == other.notes &&
          playCount == other.playCount &&
          lastPlayedAt == other.lastPlayedAt &&
          createdAt == other.createdAt &&
          updatedAt == other.updatedAt &&
          deletedAt == other.deletedAt;

  @override
  int get hashCode => Object.hash(
        id,
        title,
        Object.hashAll(artists),
        dateWritten,
        timeSig,
        keySig,
        Object.hashAll(languages),
        notes,
        playCount,
        lastPlayedAt,
        createdAt,
        updatedAt,
        deletedAt,
      );

  @override
  String toString() => 'Notation(id: $id, title: $title)';
}

/// Returns true if [a] and [b] contain the same elements in the same order.
bool _listEquals<T>(List<T> a, List<T> b) {
  if (a.length != b.length) return false;
  for (var i = 0; i < a.length; i++) {
    if (a[i] != b[i]) return false;
  }
  return true;
}
