// RenderParams domain model and NotationFilter enum.
//
// Defines the non-destructive rendering parameters stored per notation page in
// [notation_pages.render_params]. Consumed by ImageProcessingService to apply
// filter, crop, and rotation transforms at render time without mutating the
// original image file.
//
// JSON serialization is generated by json_serializable.
// Run `dart run build_runner build --delete-conflicting-outputs` to regenerate
// render_params.g.dart.

import 'package:json_annotation/json_annotation.dart';

part 'render_params.g.dart';

/// The set of non-destructive colour filters that can be applied to a notation
/// page at render time.
enum NotationFilter {
  /// No filter — display the original image colours.
  @JsonValue('none')
  none,

  /// Desaturate the image to shades of grey.
  @JsonValue('grayscale')
  grayscale,

  /// Convert the image to pure black-and-white (high-contrast).
  @JsonValue('black_and_white')
  blackAndWhite,

  /// Apply a warm (amber/sepia) colour tint.
  @JsonValue('tint_warm')
  tintWarm,

  /// Apply a cool (blue) colour tint.
  @JsonValue('tint_cool')
  tintCool,
}

/// Normalized crop region expressed as fractions of the original image
/// dimensions.
///
/// All values must be in the range [0.0, 1.0]. [left] < [right] and
/// [top] < [bottom] are expected invariants enforced by the app layer.
@JsonSerializable(fieldRename: FieldRename.snake)
class CropRect {
  /// Creates an immutable [CropRect] from normalized fractions.
  ///
  /// Parameters:
  /// - [left]: Left edge fraction (0.0 = image left edge).
  /// - [top]: Top edge fraction (0.0 = image top edge).
  /// - [right]: Right edge fraction (1.0 = image right edge).
  /// - [bottom]: Bottom edge fraction (1.0 = image bottom edge).
  const CropRect({
    required this.left,
    required this.top,
    required this.right,
    required this.bottom,
  });

  /// Left edge as a fraction of the original image width.
  final double left;

  /// Top edge as a fraction of the original image height.
  final double top;

  /// Right edge as a fraction of the original image width.
  final double right;

  /// Bottom edge as a fraction of the original image height.
  final double bottom;

  /// Deserializes a [CropRect] from a JSON map.
  factory CropRect.fromJson(Map<String, dynamic> json) =>
      _$CropRectFromJson(json);

  /// Serializes this [CropRect] to a JSON map.
  Map<String, dynamic> toJson() => _$CropRectToJson(this);

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CropRect &&
          runtimeType == other.runtimeType &&
          left == other.left &&
          top == other.top &&
          right == other.right &&
          bottom == other.bottom;

  @override
  int get hashCode => Object.hash(left, top, right, bottom);

  @override
  String toString() =>
      'CropRect(left: $left, top: $top, right: $right, bottom: $bottom)';
}

/// Immutable set of non-destructive rendering parameters for a notation page.
///
/// Stored as JSON in [notation_pages.render_params] and applied at render time
/// by [ImageProcessingService]. The original image at the page's [imagePath] is
/// never mutated.
///
/// Use [RenderParams.identity] for the no-op default (no filter, no crop,
/// no rotation).
@JsonSerializable(fieldRename: FieldRename.snake)
class RenderParams {
  /// Creates an immutable [RenderParams] instance.
  ///
  /// Parameters:
  /// - [filter]: Colour filter to apply. Defaults to [NotationFilter.none].
  /// - [rotationDegrees]: Clockwise rotation in degrees. Must be one of
  ///   0, 90, 180, or 270. Defaults to `0`.
  /// - [cropRect]: Optional normalized crop region. `null` means no crop.
  const RenderParams({
    this.filter = NotationFilter.none,
    this.rotationDegrees = 0,
    this.cropRect,
  });

  /// The no-op default with no filter, no crop, and no rotation.
  static const RenderParams identity = RenderParams();

  /// Colour filter applied to the page image at render time.
  final NotationFilter filter;

  /// Clockwise rotation in degrees.
  ///
  /// Valid values: 0, 90, 180, 270.
  final int rotationDegrees;

  /// Normalized crop region, or `null` for no cropping.
  ///
  /// When non-null, all four fields of [CropRect] are fractions in [0.0, 1.0].
  final CropRect? cropRect;

  /// Returns a copy of this [RenderParams] with the specified fields replaced.
  ///
  /// To explicitly clear [cropRect] to `null`, pass `clearCropRect: true`.
  /// Passing a new [cropRect] value takes precedence over [clearCropRect].
  ///
  /// Parameters:
  /// - [filter]: Replacement filter value.
  /// - [rotationDegrees]: Replacement rotation value.
  /// - [cropRect]: Replacement crop rect.
  /// - [clearCropRect]: When `true` and [cropRect] is not provided, sets
  ///   [cropRect] to `null`.
  RenderParams copyWith({
    NotationFilter? filter,
    int? rotationDegrees,
    CropRect? cropRect,
    bool clearCropRect = false,
  }) =>
      RenderParams(
        filter: filter ?? this.filter,
        rotationDegrees: rotationDegrees ?? this.rotationDegrees,
        cropRect: cropRect ?? (clearCropRect ? null : this.cropRect),
      );

  /// Deserializes a [RenderParams] from a JSON map.
  ///
  /// An empty map (`{}`) is treated as [RenderParams.identity].
  factory RenderParams.fromJson(Map<String, dynamic> json) =>
      _$RenderParamsFromJson(json);

  /// Serializes this [RenderParams] to a JSON map.
  ///
  /// The [cropRect] field is serialized to a nested map via [CropRect.toJson],
  /// or `null` when no crop is set.
  Map<String, dynamic> toJson() {
    final base = _$RenderParamsToJson(this);
    // The generator emits the raw CropRect object for nested types; replace it
    // with the properly serialized map so the output is JSON-safe.
    base['crop_rect'] = cropRect?.toJson();
    return base;
  }

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RenderParams &&
          runtimeType == other.runtimeType &&
          filter == other.filter &&
          rotationDegrees == other.rotationDegrees &&
          cropRect == other.cropRect;

  @override
  int get hashCode => Object.hash(filter, rotationDegrees, cropRect);

  @override
  String toString() =>
      'RenderParams(filter: $filter, rotationDegrees: $rotationDegrees, '
      'cropRect: $cropRect)';
}
