// SavedPage — input DTO for a page within a saveNotation call.
//
// Carries the data needed to persist a single notation page row. The caller
// (e.g. CaptureViewModel) is responsible for generating the UUID and copying
// the image file to its final location before calling
// NotationRepository.saveNotation.

// ---------------------------------------------------------------------------
// SavedPage
// ---------------------------------------------------------------------------

/// Immutable input DTO for a single page passed to
/// [NotationRepository.saveNotation].
///
/// The caller generates [id] (UUIDv4) and resolves [imagePath] to its final
/// on-disk relative path before handing this DTO to the repository. The
/// repository writes one [NotationPagesTable] row per [SavedPage] in the same
/// transaction as the parent [Notation] row.
final class SavedPage {
  /// Creates an immutable [SavedPage].
  ///
  /// Parameters:
  /// - [id]: UUIDv4 generated by the caller.
  /// - [pageOrder]: 0-indexed position of this page within the notation.
  /// - [imagePath]: Path relative to `getApplicationDocumentsDirectory()`.
  /// - [renderParams]: Serialised [RenderParams] JSON; defaults to `'{}'`.
  const SavedPage({
    required this.id,
    required this.pageOrder,
    required this.imagePath,
    this.renderParams = '{}',
  });

  /// UUIDv4 generated by the caller before the save call.
  final String id;

  /// 0-indexed position of this page within the parent notation.
  final int pageOrder;

  /// Path relative to `getApplicationDocumentsDirectory()`.
  ///
  /// Example: `notations/<notation_id>/page_<page_id>_original.jpg`.
  final String imagePath;

  /// Serialised [RenderParams] JSON.
  ///
  /// Contains non-destructive render settings (filter, crop rect, rotation).
  /// The original image at [imagePath] is never mutated. Defaults to `'{}'`.
  final String renderParams;

  @override
  String toString() =>
      'SavedPage(id: $id, pageOrder: $pageOrder, imagePath: $imagePath)';
}
