// Tag domain model.
//
// Immutable representation of a user-defined tag as returned by
// [TagRepository]. JSON serialization is generated by json_serializable.
//
// Run `dart run build_runner build --delete-conflicting-outputs` to regenerate
// tag.g.dart.

import 'package:json_annotation/json_annotation.dart';

part 'tag.g.dart';

/// Immutable domain model for a user-defined notation tag.
///
/// Tags categorise notations. Each tag has a unique [name] and a
/// Catppuccin [colorHex] for visual identification.
@JsonSerializable(fieldRename: FieldRename.snake)
class Tag {
  /// Creates an immutable [Tag] instance.
  ///
  /// Parameters:
  /// - [id]: UUIDv4 generated at the app layer.
  /// - [name]: Unique display name of the tag.
  /// - [colorHex]: Catppuccin hex color string, e.g. `'#f38ba8'`.
  /// - [createdAt]: ISO 8601 datetime of creation.
  /// - [updatedAt]: ISO 8601 datetime of last update.
  const Tag({
    required this.id,
    required this.name,
    required this.colorHex,
    required this.createdAt,
    required this.updatedAt,
  });

  /// UUIDv4 generated at the app layer.
  final String id;

  /// Unique display name of this tag.
  final String name;

  /// Catppuccin hex color string, e.g. `'#f38ba8'`.
  final String colorHex;

  /// ISO 8601 datetime when this tag was created.
  final String createdAt;

  /// ISO 8601 datetime of the last update to this tag.
  final String updatedAt;

  /// Returns a copy of this [Tag] with the specified fields replaced.
  ///
  /// Fields not provided retain their current values.
  Tag copyWith({
    String? id,
    String? name,
    String? colorHex,
    String? createdAt,
    String? updatedAt,
  }) =>
      Tag(
        id: id ?? this.id,
        name: name ?? this.name,
        colorHex: colorHex ?? this.colorHex,
        createdAt: createdAt ?? this.createdAt,
        updatedAt: updatedAt ?? this.updatedAt,
      );

  /// Deserializes a [Tag] from a JSON map.
  factory Tag.fromJson(Map<String, dynamic> json) => _$TagFromJson(json);

  /// Serializes this [Tag] to a JSON map.
  Map<String, dynamic> toJson() => _$TagToJson(this);

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Tag &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          colorHex == other.colorHex &&
          createdAt == other.createdAt &&
          updatedAt == other.updatedAt;

  @override
  int get hashCode => Object.hash(id, name, colorHex, createdAt, updatedAt);

  @override
  String toString() => 'Tag(id: $id, name: $name, colorHex: $colorHex)';
}
