// UserPreferences domain model.
//
// Immutable singleton representing all user-configurable application settings,
// as returned by [PreferencesRepository]. JSON serialization is generated by
// json_serializable with explicit enum converters to match the DB check
// constraints.
//
// Run `dart run build_runner build --delete-conflicting-outputs` to regenerate
// user_preferences.g.dart.

import 'package:json_annotation/json_annotation.dart';

part 'user_preferences.g.dart';

/// The app's theme brightness mode.
///
/// Mirrors the `CHECK (theme_mode IN ('light', 'dark', 'system'))` DB
/// constraint.
@JsonEnum(valueField: 'dbValue')
enum AppThemeMode {
  /// Force light theme.
  light('light'),

  /// Force dark theme.
  dark('dark'),

  /// Follow the system setting.
  system('system');

  /// Creates an [AppThemeMode] with the given database string value.
  const AppThemeMode(this.dbValue);

  /// The string value used in the database and JSON serialization.
  final String dbValue;
}

/// The source of the app's color scheme.
///
/// Mirrors the `CHECK (color_scheme_mode IN ('catppuccin', 'monet'))` DB
/// constraint.
@JsonEnum(valueField: 'dbValue')
enum ColorSchemeMode {
  /// Use a Catppuccin-based seed color.
  catppuccin('catppuccin'),

  /// Use Android 12+ wallpaper-derived dynamic color.
  monet('monet');

  /// Creates a [ColorSchemeMode] with the given database string value.
  const ColorSchemeMode(this.dbValue);

  /// The string value used in the database and JSON serialization.
  final String dbValue;
}

/// The default sort order for the notation library.
///
/// Mirrors the `CHECK (default_sort IN (...))` DB constraint.
@JsonEnum(valueField: 'dbValue')
enum SortOrder {
  /// Newest created first.
  createdAtDesc('created_at_desc'),

  /// Oldest created first.
  createdAtAsc('created_at_asc'),

  /// Most recently written first.
  dateWrittenDesc('date_written_desc'),

  /// Oldest written first.
  dateWrittenAsc('date_written_asc'),

  /// Alphabetical A → Z.
  titleAsc('title_asc'),

  /// Alphabetical Z → A.
  titleDesc('title_desc'),

  /// Most played first.
  playCountDesc('play_count_desc'),

  /// Most recently played first.
  lastPlayedAtDesc('last_played_at_desc');

  /// Creates a [SortOrder] with the given database string value.
  const SortOrder(this.dbValue);

  /// The string value used in the database and JSON serialization.
  final String dbValue;
}

/// The default library view layout.
///
/// Grid is deferred to v2 (D-25); only `list` is valid in v1.
@JsonEnum(valueField: 'dbValue')
enum ViewMode {
  /// Single-column list layout.
  list('list');

  /// Creates a [ViewMode] with the given database string value.
  const ViewMode(this.dbValue);

  /// The string value used in the database and JSON serialization.
  final String dbValue;
}

/// Immutable domain model for the singleton user preferences row.
///
/// There is exactly one [UserPreferences] in the database (enforced by
/// `CHECK (id = 1)` at the DB level). This model exposes all settings as
/// typed values rather than raw strings.
@JsonSerializable(fieldRename: FieldRename.snake)
class UserPreferences {
  /// Creates an immutable [UserPreferences] instance.
  ///
  /// Parameters:
  /// - [userName]: Display name shown in the app.
  /// - [themeMode]: Brightness mode preference.
  /// - [colorSchemeMode]: Color scheme source preference.
  /// - [seedColor]: Catppuccin hex when [colorSchemeMode] is catppuccin;
  ///   nullable.
  /// - [defaultSort]: Default sort order for the notation library.
  /// - [defaultView]: Default view layout for the notation library.
  const UserPreferences({
    required this.userName,
    required this.themeMode,
    required this.colorSchemeMode,
    this.seedColor,
    required this.defaultSort,
    required this.defaultView,
  });

  /// Display name shown in the application UI.
  final String userName;

  /// Brightness mode for the app theme.
  final AppThemeMode themeMode;

  /// Source of the color scheme (Catppuccin seed or Monet wallpaper).
  final ColorSchemeMode colorSchemeMode;

  /// Catppuccin hex color used when [colorSchemeMode] is [ColorSchemeMode.catppuccin]; nullable.
  final String? seedColor;

  /// Default sort order applied to the notation library list.
  final SortOrder defaultSort;

  /// Default view layout for the notation library.
  final ViewMode defaultView;

  /// Returns a copy of this [UserPreferences] with the specified fields
  /// replaced.
  ///
  /// Fields not provided retain their current values.
  UserPreferences copyWith({
    String? userName,
    AppThemeMode? themeMode,
    ColorSchemeMode? colorSchemeMode,
    String? seedColor,
    SortOrder? defaultSort,
    ViewMode? defaultView,
  }) =>
      UserPreferences(
        userName: userName ?? this.userName,
        themeMode: themeMode ?? this.themeMode,
        colorSchemeMode: colorSchemeMode ?? this.colorSchemeMode,
        seedColor: seedColor ?? this.seedColor,
        defaultSort: defaultSort ?? this.defaultSort,
        defaultView: defaultView ?? this.defaultView,
      );

  /// Deserializes [UserPreferences] from a JSON map.
  factory UserPreferences.fromJson(Map<String, dynamic> json) =>
      _$UserPreferencesFromJson(json);

  /// Serializes this [UserPreferences] to a JSON map.
  Map<String, dynamic> toJson() => _$UserPreferencesToJson(this);

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is UserPreferences &&
          runtimeType == other.runtimeType &&
          userName == other.userName &&
          themeMode == other.themeMode &&
          colorSchemeMode == other.colorSchemeMode &&
          seedColor == other.seedColor &&
          defaultSort == other.defaultSort &&
          defaultView == other.defaultView;

  @override
  int get hashCode => Object.hash(
        userName,
        themeMode,
        colorSchemeMode,
        seedColor,
        defaultSort,
        defaultView,
      );

  @override
  String toString() =>
      'UserPreferences(userName: $userName, themeMode: $themeMode, '
      'colorSchemeMode: $colorSchemeMode)';
}
